[[redirects]]
  from = "/themanfromhollywood/*"
  to = "https://themanfromhollywood.netlify.com/:splat"
  status = 200
  
[[redirects]]
  from = "/whatsgoingonwithcss/*"
  to = "https://whatsgoingonwithcss.netlify.com/:splat"
  status = 200
