[[redirects]]
  from = "/themanfromhollywood/*"
  to = "https://themanfromhollywood.netlify.com/:splat"
  status = 200
  
[[redirects]]
  from = "/whatsgoingonwithcss/*"
  to = "https://whatsgoingonwithcss.netlify.com/:splat"
  status = 200
  
[[redirects]]
  from = "/css-true-titles/*"
  to = "https://css-true-titles.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/overawe/*"
  to = "https://overawe.netlify.com/:splat"
  status = 200
  
[[redirects]]
  from = "/cssoff/*"
  to = "https://cssoff.netlify.com/:splat"
  status = 200
  
[[redirects]]
  from = "/css-shaky-animation/*"
  to = "https://css-squigglevision.netlify.com/:splat"
  status = 200
  
[[redirects]]
  from = "/slenderman/*"
  to = "https://slenderman.netlify.com/:splat"
  status = 200
  
[[redirects]]
  from = "/css-animated-sprites/*"
  to = "https://css-animated-sprites.netlify.com/:splat"
  status = 200
  
[[redirects]]
  from = "/css-gradient-transition-sorta/*"
  to = "https://css-gradient-transition-sorta.netlify.com/:splat"
  status = 200
  
[[redirects]]
  from = "/css-slideshows/*"
  to = "https://css-slideshows.netlify.com/:splat"
  status = 200
  
[[redirects]]
  from = "/css-write-on/*"
  to = "https://css-write-on.netlify.com/:splat"
  status = 200
  
[[redirects]]
  from = "/media-seek-from-url/*"
  to = "https://media-seek-from-url.netlify.com/:splat"
  status = 200
