[[redirects]]
  from = "/themanfromhollywood/*"
  to = "https://themanfromhollywood.netlify.com/:splat"
  status = 200
  
[[redirects]]
  from = "/whatsgoingonwithcss/*"
  to = "https://whatsgoingonwithcss.netlify.com/:splat"
  status = 200
  
[[redirects]]
  from = "/css-true-titles/*"
  to = "https://css-true-titles.netlify.com/:splat"
  status = 200

[[redirects]]
  from = "/overawe/*"
  to = "https://overawe.netlify.com/:splat"
  status = 200
